# Generated by Django 4.2.26 on 2025-11-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, default='Soldier', max_length=100)),
                ('_cookies_data', models.TextField(blank=True, default='{}')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
